{{
    config(
        materialized='table',
        database='NZ_EV_ANALYSIS',
        schema='INTEGRATION'
    )
}}
with flattened_data as (
select 
J.CHARGIN_STATIONS:OBJECTID :: INTEGER AS OBJECTID,
J.CHARGIN_STATIONS:NAME :: VARCHAR AS NAME,
J.CHARGIN_STATIONS:OPERATOR :: VARCHAR AS OPERATOR,
J.CHARGIN_STATIONS:OWNER :: VARCHAR AS OWNER,
J.CHARGIN_STATIONS:ADDRESS :: VARCHAR AS ADDRESS,
J.CHARGIN_STATIONS:is24Hours :: BOOLEAN AS IS_24HOURS,
J.CHARGIN_STATIONS:carParkCount :: INTEGER AS CARPARK_COUNT,
J.CHARGIN_STATIONS:hasCarparkCost :: BOOLEAN AS HAS_CARPARK_COST,
J.CHARGIN_STATIONS:maxTimeLimit :: VARCHAR AS MAX_TIME_LIMIT,
J.CHARGIN_STATIONS:hasTouristAttraction :: BOOLEAN AS HAS_TOURIST_ATTRACTION,
J.CHARGIN_STATIONS:latitude :: FLOAT AS LATITUDE,
J.CHARGIN_STATIONS:longitude :: FLOAT AS LONGITUDE,
J.CHARGIN_STATIONS:currentType :: VARCHAR AS CURRENT_TYPE,
to_date(J.CHARGIN_STATIONS:dateFirstOperational :: VARCHAR,'DD/MM/YYYY') AS DATE_FIRST_OPERATIONAL,
J.CHARGIN_STATIONS:numberOfConnectors :: integer AS NUMBER_OF_CONNECTORS,
J.CHARGIN_STATIONS:connectorsList :: VARCHAR AS CONNECTORS_LIST,
J.CHARGIN_STATIONS:hasChargingCost :: BOOLEAN AS HAS_CHARGING_COST,
J.CHARGIN_STATIONS:GlobalID :: VARCHAR AS GLOBAL_ID,
J.SYSTEM_FILE_NAME,J.SYSTEM_FILE_ROW_NUMBER,CURRENT_TIMESTAMP,CURRENT_USER
from {{ source('NZ_EV_ANALYSIS', 'EV_ROAM_CHARING_STATIONS_JSON') }} j
)

select *
from flattened_data